name: CI/CD Pipeline for Android App

on:
  push:
    branches:
      - Tracking-app  # Trigger the pipeline on pushes to the Tracking-app branch
  pull_request:
    branches:
      - Tracking-app  # Trigger for pull requests targeting the Tracking-app branch
  workflow_dispatch:

permissions:
  contents: write  # Grant write access to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 8 (as you are using it)
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        run: |
          # Install Android command line tools and set up the SDK
          sudo mkdir -p /usr/local/lib/android/sdk
          sudo chown $USER:$USER /usr/local/lib/android/sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /usr/local/lib/android/sdk
          sudo rm -rf /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo mv /usr/local/lib/android/sdk/cmdline-tools/* /usr/local/lib/android/sdk/cmdline-tools/latest/

          echo "export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "export PATH=\$PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_ENV

      # Step 4: Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Step 5: Decode keystore from GitHub secrets and place it in the correct directory
      - name: Decode keystore from GitHub secrets
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p ./app/KEY_STORE
          echo "${KEYSTORE_BASE64}" | base64 --decode > ./app/KEY_STORE/Ecorvi_Tracking_App_New.jks

      # Step 6: Build the Release APK
      - name: Build the project
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}  # Set the key alias from secrets
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}  # Set the key password from secrets
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}  # Set the store password from secrets
        run: ./gradlew assembleRelease

      # Step 7: Upload the APK to GitHub Releases
      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: "Release of APK version v${{ github.run_number }}"
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is set
